spring:
  datasource:
    url: jdbc:mysql:///edu_ai?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 12345
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.phil.entity

server:
  url: http://localhost:8080  # 根据你的实际服务器地址修改

file:
  upload-dir: ./uploads  # 根据你的实际文件上传目录修改




